
#General Config Section. See https://readme.firstdarkdev.xyz/simple-rpc/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = 999279245341773924
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 18

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = false
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = [""]
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = false
	#The first line of text under the app name
	description = ""
	#The seconds line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = [""]
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = false
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = [""]
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = false
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = [""]
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = false
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = [""]
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = false
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = [""]
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = false
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = [""]
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = false
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = [""]
	#The text that gets displayed when the large image is hovered
	largeImageText = ""
	#The Asset ID of the image to display as the small image
	smallImageKey = [""]
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Astralium • Optimized modifications being an ecosystem"
	#The second line of text under the app name
	state = "It's not just for games, follow our news"
	#The Asset ID of the image to display as the large image
	largeImageKey = ["astraliummc"]
	#The text that gets displayed when the large image is hovered
	largeImageText = "AstraliumClient • 1.19.3 "
	#The Asset ID of the image to display as the small image
	smallImageKey = ["astraliummc"]
	#The text that gets displayed when the small image is hovered
	smallImageText = "Version • v193-2 • Branch • Beta"
	#The buttons to display on Discord
	[[generic.buttons]]
		label = "Github"
		url = "https://github.com/AstraliumMC"
	# [[generic.buttons]]
	# 	label = "Discord"
	# 	url = "https://discord.gg/7XkGYJbtZg"
	[[generic.buttons]]
		label = "Modrinth"
		url = "https://modrinth.com/modpack/astralium-client-for-best-optimization"

#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = ""
		state = ""
		largeImageKey = ["overworld"]
		largeImageText = ""
		smallImageKey = ["astraliummc"]
		smallImageText = ""
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = ""
		state = ""
		largeImageKey = ["nether"]
		largeImageText = ""
		smallImageKey = ["astraliummc"]
		smallImageText = ""
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = ""
		state = ""
		largeImageKey = ["end"]
		largeImageText = ""
		smallImageKey = ["astraliummc"]
		smallImageText = ""
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = ""
		state = ""
		largeImageKey = ["overworld"]
		largeImageText = ""
		smallImageKey = ["astraliummc"]
		smallImageText = ""
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = ""
		state = ""
		largeImageKey = ["nether"]
		largeImageText = ""
		smallImageKey = ["astraliummc"]
		smallImageText = ""
		buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = ""
		state = ""
		largeImageKey = ["end"]
		largeImageText = ""
		smallImageKey = ["astraliummc"]
		smallImageText = ""
		buttons = []

